Rehber.MVC/Models/AdresViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Rehber.MVC.Models
{
    public class AdresViewModel
    {
        public int AdresID { get; set; }
        [Required(ErrorMessage ="İl alanı boş geçilemez")]
        [MaxLength(20,ErrorMessage ="İl alanı maksimum 20 karakter olabilir")]
        public string Il { get; set; }
        [Required(ErrorMessage = "İlçe alanı boş geçilemez")]
        [MaxLength(20, ErrorMessage = "İlçe alanı maksimum 20 karakter olabilir")]
        public string Ilce { get; set; }
        public int KisiID { get; set; }
    }
}

Rehber.MVC/Controllers/AdresController.cs
using Rehber.DAL.KisiService;
using Rehber.Entities.Entities;
using Rehber.MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Rehber.MVC.Controllers
{
    public class AdresController : Controller
    {
        // GET: Adres
        AdresManager _adresManager;
        KisiManager _kisiManager;
        public AdresController()
        {
            _adresManager = new AdresManager();
            _kisiManager = new KisiManager();
        }

        //Kişileri getiren bir dropdown yapıp
        //ViewBag ile sayfama taşıma işlemi yapıcam
        public List<SelectListItem> DropDownDoldur()
        {
            List<SelectListItem> kisiListesi = (from p in _kisiManager.GetAllKisi().ToList()
                                            select new SelectListItem
                                            {
                                                Text = p.Adi + " " + p.Soyadi,
                                                Value = p.KisiID.ToString()
                                            }).ToList();
            return kisiListesi;

        }
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult AdresEkle()
        {
            ViewBag.KisiListesi = DropDownDoldur();
            return View();
        }
        [HttpPost]
        public ActionResult AdresEkle(AdresViewModel adresvm)
        {

            TempData["Message"] = _adresManager.AddAdres(new Adres {
                Il = adresvm.Il,
                Ilce=adresvm.Ilce,
                KisiID=adresvm.KisiID
            
            });
            return RedirectToAction("../Home/Index");
        }



        //Güncelleme işlemi için sayfaya verilerimi çekicek kısım
        [HttpGet]
        public ActionResult AdressGuncelle(int Id)// As per coding guidlin Id should be id so its look like  public ActionResult AdressGuncelle(int id)
        {
            ViewBag.KisiListesi = DropDownDoldur();
            var adres = _adresManager.GetAllAdres(x => x.AdresID == Id);
            AdresViewModel adrsvm = new AdresViewModel
            {
                AdresID = adres.FirstOrDefault().AdresID,
                Il = adres.FirstOrDefault().Il,
                Ilce = adres.FirstOrDefault().Ilce,
                KisiID = adres.FirstOrDefault().KisiID
            };
            return View(adrsvm);
        }
        [HttpPost]
        public ActionResult AdressGuncelle(AdresViewModel adresvm)
        {
            Adres ad = new Adres
            {
                AdresID = adresvm.AdresID,
                Il = adresvm.Il,
                Ilce = adresvm.Ilce,
                KisiID = adresvm.KisiID
            };
            TempData["Message"] = _adresManager.UpdateAdres(ad);
            return RedirectToAction("../Home/Index");
        }
        [HttpGet]
        public ActionResult AdresSil(int id)
        {
            var adres = _adresManager.GetAllAdres(x => x.AdresID == id);
            AdresViewModel ads = new AdresViewModel
            {
                AdresID = adres.FirstOrDefault().AdresID,
                Il = adres.FirstOrDefault().Il,
                Ilce = adres.FirstOrDefault().Ilce,
                KisiID = adres.FirstOrDefault().KisiID
            };
            var Kisi = _kisiManager.GetAllKisi(x => x.KisiID == ads.KisiID).FirstOrDefault();
            ViewBag.AdSoyad = Kisi.Adi + " " + Kisi.Soyadi;
            return View(ads);
        }
        [HttpPost]
        [ActionName("AdresSil")]
        public ActionResult AdressSilinsinMi(int id)
        {
            Adres adres = _adresManager.GetAllAdres(x => x.AdresID == id).FirstOrDefault();
            TempData["Message"] = _adresManager.DeleteAdres(adres);
            return RedirectToAction("../Home/Index");
        }
        
    }
}

Rehber.MVC/Views/Adres/AdresEkle.cshtml
@model Rehber.MVC.Models.AdresViewModel

@{
    ViewBag.Title = "AdresEkle";
}

<h2>AdresEkle</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AdresViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Il, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Il, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Il, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ilce, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ilce, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ilce, "", new { @class = "text-danger" })
            </div>
        </div>        
        
        <div class="form-group">
            @Html.LabelFor(model => model.KisiID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.KisiID,(IEnumerable<SelectListItem>)ViewBag.KisiListesi, new { htmlAttributes = new { @class = "form-control" } })

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Rehber.MVC/Views/Adres/AdresSil.cshtml
@model Rehber.MVC.Models.AdresViewModel

@{
    ViewBag.Title = "AdresSil";
}

<h2>AdresSil</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AdresViewModel</h4>
    <hr />
    @using (Html.BeginForm("AdresSil", "Adres", FormMethod.Post))
    { @Html.AntiForgeryToken()
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Il)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Il)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ilce)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ilce)
        </dd>
        @ViewBag.AdSoyad

    </dl>



        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Rehber.MVC/Views/Adres/AdressGuncelle.cshtml
@model Rehber.MVC.Models.AdresViewModel

@{
    ViewBag.Title = "AdressGuncelle";
}

<h2>AdressGuncelle</h2>

@using (Html.BeginForm("AdressGuncelle", "Adres",FormMethod.Post))
{
    @Html.HiddenFor(model=>model.AdresID)
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>AdresViewModel</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Il, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Il, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Il, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Ilce, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Ilce, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Ilce, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.KisiID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.KisiID, (IEnumerable<SelectListItem>)ViewBag.KisiListesi, new { htmlAttributes = new { @class = "form-control" } })

        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>