Rehber.MVC/Models/KisiViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Rehber.MVC.Models
{
    public class KisiViewModel
    {
        public int KisiID { get; set; }
        [Required(ErrorMessage = "Ad alanı boş geçilemez")]
        [MaxLength(50, ErrorMessage = "Ad alanı maksimum 50 karakter olabilir")]
        public string Ad { get; set; }
        [Required(ErrorMessage = "Soyad alanı boş geçilemez")]
        [MaxLength(20, ErrorMessage = "Soyad alanı maksimum 20 karakter olabilir")]
        public string Soyadi { get; set; }
        [Required(ErrorMessage = "Yaş alanı boş geçilemez")]
        [Range(10,60, ErrorMessage = "Yaş alanı maksimum 10 ile 60 arasında olabilir")]
        public int Yas { get; set; }
    }
}

Rehber.MVC/Controllers/KisiController.cs
using Rehber.DAL.KisiService;
using Rehber.Entities.Entities;
using Rehber.MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Rehber.MVC.Controllers
{
    public class KisiController : Controller
    {
        // GET: Kisi
        KisiManager _kisiManager;
        public KisiController()
        {
            _kisiManager = new KisiManager();
        }
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult KisiEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult KisiEkle(KisiViewModel kisiVM)
        {

            string mesaj = _kisiManager.AddKisi(new Kisi { Adi = kisiVM.Ad, Soyadi = kisiVM.Soyadi, Yas = kisiVM.Yas });
            TempData["Message"] = mesaj;

            return RedirectToAction("../Home/Index");
        }

        [HttpGet]
        public ActionResult KisiGuncelle(int id)
        {
            var kisi = _kisiManager.GetAllKisi(x => x.KisiID == id);
            KisiViewModel k = new KisiViewModel
            {
                KisiID = kisi.FirstOrDefault().KisiID,
                Ad = kisi.FirstOrDefault().Adi,
                Soyadi = kisi.FirstOrDefault().Soyadi,
                Yas = kisi.FirstOrDefault().Yas
            };
            return View(k);
        }
        [HttpPost]
        public ActionResult KisiGuncelle(KisiViewModel k)
        {
            Kisi kisi = new Kisi
            {
                KisiID = k.KisiID,
                Adi = k.Ad,
                Soyadi = k.Soyadi,
                Yas = k.Yas
            };
            TempData["Message"] = _kisiManager.UpdateKisi(kisi);
            return RedirectToAction("../Home/Index");
        }
        [HttpGet]
        public ActionResult KisiSil(int id)
        {
            var kisi = _kisiManager.GetAllKisi(x => x.KisiID == id);
            KisiViewModel k = new KisiViewModel
            {
                KisiID = kisi.FirstOrDefault().KisiID,
                Ad = kisi.FirstOrDefault().Adi,
                Soyadi = kisi.FirstOrDefault().Soyadi,
                Yas = kisi.FirstOrDefault().Yas
            };
            return View(k);
        }
        [HttpPost]
        [ActionName("KisiSil")]
        public ActionResult KisiSilinsinMi(int id)
        {

            Kisi kisi = _kisiManager.GetAllKisi(x => x.KisiID == id).FirstOrDefault();
            TempData["Message"] = _kisiManager.DeleteKisi(kisi);
            return RedirectToAction("../Home/Index");
        }
    }
}

Rehber.MVC/Views/Kisi/KisiEkle.cshtml
@model Rehber.MVC.Models.KisiViewModel

@{
    ViewBag.Title = "KisiEkle";
}

<h2>KisiEkle</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>KisiViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Ad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Soyadi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Soyadi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Soyadi, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Yas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Yas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Yas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Rehber.MVC/Views/Kisi/KisiGuncelle.cshtml
@model Rehber.MVC.Models.KisiViewModel

@{
    ViewBag.Title = "KisiGuncelle";
}

<h2>KisiGuncelle</h2>

@using (Html.BeginForm("KisiGuncelle","Kisi",FormMethod.Post))
{
    @Html.HiddenFor(model=>model.KisiID)
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>KisiViewModel</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Ad, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Ad, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Ad, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Soyadi, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Soyadi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Soyadi, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Yas, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Yas, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Yas, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Rehber.MVC/Views/Kisi/KisiSil.cshtml
@model Rehber.MVC.Models.KisiViewModel

@{
    ViewBag.Title = "KisiSil";
}

<h2>KisiSil</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>KisiViewModel</h4>
    <hr />
    @using (Html.BeginForm("KisiSil","Kisi",FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Ad)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Ad)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Soyadi)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Soyadi)
            </dd>

        </dl>



        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>